# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_testcore.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_testcore.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f"Hello {to}!"

# %% ../nbs/00_testcore.ipynb 7
def foo(): pass
